export const products = [
  {
    id: "1",
    name: "Cloud Wing - Ultra Black Mascara",
    slug: "cloud-wing-ultra-black-mascara",
    price: 32000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Cloud+Wing",
    category: "Mascara",
    description: "Our best-selling ultra-black mascara for dramatic volume.",
  },
  {
    id: "2",
    name: "Girl Gang - Lip Gloss",
    slug: "girl-gang-lip-gloss",
    price: 24000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Girl+Gang",
    category: "Lip",
    description: "Hydrating lip gloss with a subtle pink tint.",
  },
  {
    id: "3",
    name: "Proof Waterproof Primer",
    slug: "proof-waterproof-primer",
    price: 38000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Proof+Primer",
    category: "Primer",
    description: "24-hour waterproof primer for all-day wear.",
  },
  {
    id: "4",
    name: "Cloud Paint - Rosy",
    slug: "cloud-paint-rosy",
    price: 28000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Cloud+Paint",
    category: "Blush",
    description: "Cream blush for a natural, dewy glow.",
  },
  {
    id: "5",
    name: "Skin Savvy - Daily Moisturizer",
    slug: "skin-savvy-daily-moisturizer",
    price: 42000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Skin+Savvy",
    category: "Skincare",
    description: "Lightweight daily moisturizer with SPF 30.",
  },
  {
    id: "6",
    name: "Ooh Lash Lift",
    slug: "ooh-lash-lift",
    price: 36000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Ooh+Lash",
    category: "Mascara",
    description: "Instant lash lift serum and mascara.",
  },
  {
    id: "7",
    name: "Kiss For Day - Lip Balm",
    slug: "kiss-for-day-lip-balm",
    price: 18000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Kiss+For+Day",
    category: "Lip",
    description: "Hydrating lip balm with vitamin E.",
  },
  {
    id: "8",
    name: "Eyes On You - Eye Pencil",
    slug: "eyes-on-you-eye-pencil",
    price: 22000,
    image: "https://placehold.co/400x500/f5f5f5/000?text=Eyes+On+You",
    category: "Eyes",
    description: "Waterproof eye pencil for precise lines.",
  },
];

export const blogPosts = [
  {
    slug: "clean-beauty-101",
    title: "Clean Beauty 101: What It Really Means",
    excerpt: "Understanding what clean beauty means and why it matters.",
    content: "Clean beauty refers to products made without harmful ingredients...",
    date: "2026-04-10",
  },
  {
    slug: "sustainable-packaging",
    title: "Our Commitment to Sustainable Packaging",
    excerpt: "How we're reducing plastic waste one bottle at a time.",
    content: "Sustainability is at the core of everything we do...",
    date: "2026-04-05",
  },
  {
    slug: "vegan-cruelty-free",
    title: "Vegan & Cruelty-Free: More Than Labels",
    excerpt: "Why we never test on animals and never will.",
    content: "Being vegan isn't just a marketing term for us...",
    date: "2026-03-28",
  },
];